#
# Deploy ACS Stackrox operator to all clusters
#
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acs-operator
  namespace: stackrox
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - acs-operator
---
#
# apply acs operator subscription and namespaces
#
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acs-operator
  namespace: stackrox
  labels:
    app: acs-operator
  annotations:
    apps.open-cluster-management.io/git-path: applications/acs
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: azure-openshiftacm-ns/azure-openshiftacm
  placement:
    placementRef:
      kind: PlacementRule
      name: all-managed-clusters
