kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'open-cluster-management:subscription-admin'
subjects:
  - kind: User
    name: kube:admin
  - kind: User
    name: system:admin
  - kind: User
    name: system:serviceaccount:local-acm-subscription:root-subscription-owner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'open-cluster-management:subscription-admin'
